In [98]:
import pandas as pd

In [99]:
df=pd.read_csv("E:/New folder/Data Analytics project2/new_retail_data.csv")

In [100]:
df.head()

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,...,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788.0,37249.0,Michelle Harrington,Ebony39@gmail.com,1.414787e+09,3959 Amanda Burgs,Dortmund,Berlin,77985.0,Germany,...,324.086270,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.0,Cycling shorts
1,2174773.0,69749.0,Kelsey Hill,Mark36@gmail.com,6.852900e+09,82072 Dawn Centers,Nottingham,England,99071.0,UK,...,806.707815,Electronics,Samsung,Tablet,Excellent,Standard,Credit Card,Processing,4.0,Lenovo Tab
2,6679610.0,30192.0,Scott Jensen,Shane85@gmail.com,8.362160e+09,4133 Young Canyon,Geelong,New South Wales,75929.0,Australia,...,1063.432799,Books,Penguin Books,Children's,Average,Same-Day,Credit Card,Processing,2.0,Sports equipment
3,7232460.0,62101.0,Joseph Miller,Mary34@gmail.com,2.776752e+09,8148 Thomas Creek Suite 100,Edmonton,Ontario,88420.0,Canada,...,2466.854021,Home Decor,Home Depot,Tools,Excellent,Standard,PayPal,Processing,4.0,Utility knife
4,4983775.0,27901.0,Debra Coleman,Charles30@gmail.com,9.098268e+09,5813 Lori Ports Suite 269,Bristol,England,48704.0,UK,...,248.553049,Grocery,Nestle,Chocolate,Bad,Standard,Cash,Shipped,1.0,Chocolate cookies

In [101]:
df.shape

(302010, 30)

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302010 entries, 0 to 302009
Data columns (total 30 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction_ID    301677 non-null  float64
 1   Customer_ID       301702 non-null  float64
 2   Name              301628 non-null  object
 3   Email             301663 non-null  object
 4   Phone             301648 non-null  float64
 5   Address           301695 non-null  object
 6   City              301762 non-null  object
 7   State             301729 non-null  object
 8   Zipcode           301670 non-null  float64
 9   Country           301739 non-null  object
 10  Age               301837 non-null  float64
 11  Gender            301693 non-null  object
 12  Income            301720 non-null  object
 13  Customer_Segment  301795 non-null  object
 14  Date              301651 non-null  object
 15  Year              301660 non-null  float64
 16  Month             301737 non-null  object
 17  Time              301660 non-null  object
 18  Total_Purchases   301649 non-null  float64
 19  Amount            301653 non-null  float64
 20  Total_Amount      301660 non-null  float64
 21  Product_Category  301727 non-null  object
 22  Product_Brand     301729 non-null  object
 23  Product_Type      302010 non-null  object
 24  Feedback          301826 non-null  object
 25  Shipping_Method   301673 non-null  object
 26  Payment_Method    301713 non-null  object
 27  Order_Status      301775 non-null  object
 28  Ratings           301826 non-null  float64
 29  products          302010 non-null  object
dtypes: float64(10), object(20)
memory usage: 69.1+ MB

In [103]:
df.isnull().sum()

Transaction_ID      333
Customer_ID         308
Name                382
Email               347
Phone               362
Address             315
City                248
State               281
Zipcode             340
Country             271
Age                 173
Gender              317
Income              290
Customer_Segment    215
Date                359
Year                350
Month               273
Time                350
Total_Purchases     361
Amount              357
Total_Amount        350
Product_Category    283
Product_Brand       281
Product_Type          0
Feedback            184
Shipping_Method     337
Payment_Method      297
Order_Status        235
Ratings             184
products              0
dtype: int64

In [104]:
df[df.duplicated()]

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,...,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
299759,4476510.0,20103.0,Christine Kim,James11@gmail.com,2.383778e+09,8176 Randy Squares Apt. 772,Kitchener,Ontario,7099.0,Canada,...,940.619277,Clothing,Adidas,T-shirt,Bad,Express,Credit Card,Processing,1.0,Off-the-shoulder tee
301094,5340129.0,29920.0,Collin Davis,Courtney47@gmail.com,4.087767e+09,371 Cynthia Drives Suite 699,Wollongong,New South Wales,47758.0,Australia,...,2201.568075,Grocery,Pepsi,Soft Drink,Excellent,Express,Cash,Delivered,4.0,Fruit punch
301362,4942326.0,25416.0,Pamela Martin,Christine83@gmail.com,6.657934e+09,9851 Myers Tunnel,Leicester,England,57655.0,UK,...,1535.255087,Clothing,Adidas,Jacket,Average,Same-Day,Cash,Pending,2.0,Varsity jacket
301486,3200766.0,49598.0,Mikayla Mueller,Kenneth43@gmail.com,6.980439e+09,716 Joshua Rapids Apt. 790,Bremen,Berlin,64747.0,Germany,...,2450.946762,Grocery,Pepsi,Soft Drink,Bad,Standard,Cash,Pending,1.0,Iced tea

In [105]:
df=df.drop_duplicates()

In [106]:
df['Transaction_ID'].duplicated().sum()

np.int64(7544)

In [107]:
df.drop_duplicates(subset='Transaction_ID',inplace=True)

In [108]:
df.dropna(subset=['Transaction_ID'], inplace=True)

In [109]:
df.dropna(subset=['Customer_ID'], inplace=True)

In [110]:
df['Ratings']=df.groupby('Product_Type')['Ratings'].transform(lambda x: x.fillna(x.median()))

In [111]:
df['Time']=df['Time'].fillna(df['Time'].mode()[0])

In [112]:
df['Date']=df['Date'].fillna(method='ffill')

C:\Users\parih\AppData\Local\Temp\ipykernel_6296\3582742583.py:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df['Date']=df['Date'].fillna(method='ffill')

In [113]:
df['Date']=df['Date'].str.replace('-','/')

In [114]:
df['Date']=pd.to_datetime(df['Date'])

In [115]:
df['Year']=df['Date'].dt.year

In [116]:
df['Month']=df['Date'].dt.month_name()

In [117]:
df['Gender']=df.groupby('Product_Category')['Gender'].transform(lambda x:x.fillna(x.mode()))

In [118]:
df['Name']=df['Name'].fillna('Unknown')

In [119]:
df['Email']=df['Email'].fillna('Not available')

In [120]:
df['Address']=df['Address'].fillna('Unknown')

In [121]:
df['City']=df['City'].fillna(df['City'].mode())

In [122]:
df['Age']=df['Age'].fillna(df['Age'].median())

In [123]:
df['Phone']=df['Phone'].fillna('Not Available')

In [124]:
df['State']=df['State'].fillna(df['State'].mode()[0])

In [125]:
df['Zipcode']=df['Zipcode'].fillna(-1)

In [126]:
df['Country']=df['Country'].fillna(df['Country'].mode()[0])

In [127]:
df['Customer_Segment']=df['Customer_Segment'].fillna('Unknown')

In [128]:
df['Product_Category']=df['Product_Category'].fillna('Unknown')

In [129]:
df['Feedback']=df['Feedback'].fillna('Unknown')

In [130]:
df['Product_Brand']=df['Product_Brand'].fillna('Unknown')

In [131]:
df['Shipping_Method']=df['Shipping_Method'].fillna('Unknown')

In [132]:
df['Payment_Method']=df['Payment_Method'].fillna('Unknown')

In [133]:
df['Order_Status']=df['Order_Status'].fillna('Unknown')

In [134]:
df.isnull().sum()

Transaction_ID        0
Customer_ID           0
Name                  0
Email                 0
Phone                 0
Address               0
City                244
State                 0
Zipcode               0
Country               0
Age                   0
Gender              585
Income              282
Customer_Segment      0
Date                  0
Year                  0
Month                 0
Time                  0
Total_Purchases     354
Amount              347
Total_Amount        342
Product_Category      0
Product_Brand         0
Product_Type          0
Feedback              0
Shipping_Method       0
Payment_Method        0
Order_Status          0
Ratings               0
products              0
dtype: int64

In [135]:
df.dropna(inplace=True)

In [136]:
df.shape

(292013, 30)

In [137]:
df[['Transaction_ID', 'Customer_ID','Zipcode','Age','Year','Total_Purchases']]=df[['Transaction_ID', 'Customer_ID','Zipcode','Age','Year','Total_Purchases']].astype('int64')

In [138]:
df

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,...,Total_Amount,Product_Category,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products
0,8691788,37249,Michelle Harrington,Ebony39@gmail.com,1414786801.0,3959 Amanda Burgs,Dortmund,Berlin,77985,Germany,...,324.086270,Clothing,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.0,Cycling shorts
1,2174773,69749,Kelsey Hill,Mark36@gmail.com,6852899987.0,82072 Dawn Centers,Nottingham,England,99071,UK,...,806.707815,Electronics,Samsung,Tablet,Excellent,Standard,Credit Card,Processing,4.0,Lenovo Tab
2,6679610,30192,Scott Jensen,Shane85@gmail.com,8362160449.0,4133 Young Canyon,Geelong,New South Wales,75929,Australia,...,1063.432799,Books,Penguin Books,Children's,Average,Same-Day,Credit Card,Processing,2.0,Sports equipment
3,7232460,62101,Joseph Miller,Mary34@gmail.com,2776751724.0,8148 Thomas Creek Suite 100,Edmonton,Ontario,88420,Canada,...,2466.854021,Home Decor,Home Depot,Tools,Excellent,Standard,PayPal,Processing,4.0,Utility knife
4,4983775,27901,Debra Coleman,Charles30@gmail.com,9098267635.0,5813 Lori Ports Suite 269,Bristol,England,48704,UK,...,248.553049,Grocery,Nestle,Chocolate,Bad,Standard,Cash,Shipped,1.0,Chocolate cookies
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299652,4466731,96551,Angela Graham,John16@gmail.com,2921630596.0,613 Diaz Flat,Portland,Hawaii,96841,USA,...,2676.212987,Grocery,Pepsi,Juice,Excellent,Standard,Credit Card,Processing,5.0,Grapefruit juice
299653,1234470,35598,William Barber,James77@gmail.com,4763756677.0,5558 Matthew Flats Apt. 496,Austin,Montana,59603,USA,...,1563.375261,Electronics,Apple,Smartphone,Average,Standard,Credit Card,Processing,2.0,Nokia
299654,7157113,25148,Darlene Gomez,Teresa61@gmail.com,1114925786.0,572 Wagner Forge,Adelaide,New South Wales,83497,Australia,...,193.549487,Books,HarperCollins,Fiction,Bad,Standard,Credit Card,Delivered,1.0,Thriller
299655,4733214,64906,Joanne Robinson,Emily29@gmail.com,5695197895.0,197 Donna Lodge Apt. 673,Melbourne,New South Wales,22949,Australia,...,4154.162595,Grocery,Nestle,Snacks,Average,Express,Credit Card,Processing,2.0,Trail mix
299656,8201755,48417,Kayla Stanley,Cindy37@gmail.com,5923171815.0,6026 Quinn Row Suite 313,Windsor,Ontario,68285,Canada,...,2468.016337,Electronics,Sony,Smartphone,Average,Standard,Credit Card,Shipped,2.0,Xiaomi Mi

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 292013 entries, 0 to 299656
Data columns (total 30 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Transaction_ID    292013 non-null  int64
 1   Customer_ID       292013 non-null  int64
 2   Name              292013 non-null  object
 3   Email             292013 non-null  object
 4   Phone             292013 non-null  object
 5   Address           292013 non-null  object
 6   City              292013 non-null  object
 7   State             292013 non-null  object
 8   Zipcode           292013 non-null  int64
 9   Country           292013 non-null  object
 10  Age               292013 non-null  int64
 11  Gender            292013 non-null  object
 12  Income            292013 non-null  object
 13  Customer_Segment  292013 non-null  object
 14  Date              292013 non-null  datetime64[ns]
 15  Year              292013 non-null  int64
 16  Month             292013 non-null  object
 17  Time              292013 non-null  object
 18  Total_Purchases   292013 non-null  int64
 19  Amount            292013 non-null  float64
 20  Total_Amount      292013 non-null  float64
 21  Product_Category  292013 non-null  object
 22  Product_Brand     292013 non-null  object
 23  Product_Type      292013 non-null  object
 24  Feedback          292013 non-null  object
 25  Shipping_Method   292013 non-null  object
 26  Payment_Method    292013 non-null  object
 27  Order_Status      292013 non-null  object
 28  Ratings           292013 non-null  float64
 29  products          292013 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(6), object(20)
memory usage: 69.1+ MB

In [140]:
df.columns

Index(['Transaction_ID', 'Customer_ID', 'Name', 'Email', 'Phone', 'Address',
       'City', 'State', 'Zipcode', 'Country', 'Age', 'Gender', 'Income',
       'Customer_Segment', 'Date', 'Year', 'Month', 'Time', 'Total_Purchases',
       'Amount', 'Total_Amount', 'Product_Category', 'Product_Brand',
       'Product_Type', 'Feedback', 'Shipping_Method', 'Payment_Method',
       'Order_Status', 'Ratings', 'products'],
      dtype='object')

In [141]:
df[(df['Age']<12) | (df['Age']>100)]

Empty DataFrame
Columns: [Transaction_ID, Customer_ID, Name, Email, Phone, Address, City, State, Zipcode, Country, Age, Gender, Income, Customer_Segment, Date, Year, Month, Time, Total_Purchases, Amount, Total_Amount, Product_Category, Product_Brand, Product_Type, Feedback, Shipping_Method, Payment_Method, Order_Status, Ratings, products]
Index: []

[0 rows x 30 columns]

In [142]:
df[df['Amount']<0]

Empty DataFrame
Columns: [Transaction_ID, Customer_ID, Name, Email, Phone, Address, City, State, Zipcode, Country, Age, Gender, Income, Customer_Segment, Date, Year, Month, Time, Total_Purchases, Amount, Total_Amount, Product_Category, Product_Brand, Product_Type, Feedback, Shipping_Method, Payment_Method, Order_Status, Ratings, products]
Index: []

[0 rows x 30 columns]

In [143]:
df[(df['Ratings']>5) | (df['Ratings']<0)]

Empty DataFrame
Columns: [Transaction_ID, Customer_ID, Name, Email, Phone, Address, City, State, Zipcode, Country, Age, Gender, Income, Customer_Segment, Date, Year, Month, Time, Total_Purchases, Amount, Total_Amount, Product_Category, Product_Brand, Product_Type, Feedback, Shipping_Method, Payment_Method, Order_Status, Ratings, products]
Index: []

[0 rows x 30 columns]

In [144]:
df['Age_Group']=pd.qcut(df['Age'],q=4,labels=['Young','Adult','Middle Age','Senior'])

In [191]:
hour = pd.to_timedelta(df['Time']).dt.components['hours']
bins=[0,4,12,16,20,24]
labels=['midnight','morning','afternoon','evening','night']
df['time_period']=pd.cut(hour,bins=bins,labels=labels)

In [192]:
df

,Transaction_ID,Customer_ID,Name,Email,Phone,Address,City,State,Zipcode,Country,...,Product_Brand,Product_Type,Feedback,Shipping_Method,Payment_Method,Order_Status,Ratings,products,Age_Group,time_period
0,8691788,37249,Michelle Harrington,Ebony39@gmail.com,1414786801.0,3959 Amanda Burgs,Dortmund,Berlin,77985,Germany,...,Nike,Shorts,Excellent,Same-Day,Debit Card,Shipped,5.0,Cycling shorts,Young,night
1,2174773,69749,Kelsey Hill,Mark36@gmail.com,6852899987.0,82072 Dawn Centers,Nottingham,England,99071,UK,...,Samsung,Tablet,Excellent,Standard,Credit Card,Processing,4.0,Lenovo Tab,Young,morning
2,6679610,30192,Scott Jensen,Shane85@gmail.com,8362160449.0,4133 Young Canyon,Geelong,New South Wales,75929,Australia,...,Penguin Books,Children's,Average,Same-Day,Credit Card,Processing,2.0,Sports equipment,Senior,midnight
3,7232460,62101,Joseph Miller,Mary34@gmail.com,2776751724.0,8148 Thomas Creek Suite 100,Edmonton,Ontario,88420,Canada,...,Home Depot,Tools,Excellent,Standard,PayPal,Processing,4.0,Utility knife,Senior,afternoon
4,4983775,27901,Debra Coleman,Charles30@gmail.com,9098267635.0,5813 Lori Ports Suite 269,Bristol,England,48704,UK,...,Nestle,Chocolate,Bad,Standard,Cash,Shipped,1.0,Chocolate cookies,Young,afternoon
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
299652,4466731,96551,Angela Graham,John16@gmail.com,2921630596.0,613 Diaz Flat,Portland,Hawaii,96841,USA,...,Pepsi,Juice,Excellent,Standard,Credit Card,Processing,5.0,Grapefruit juice,Middle Age,morning
299653,1234470,35598,William Barber,James77@gmail.com,4763756677.0,5558 Matthew Flats Apt. 496,Austin,Montana,59603,USA,...,Apple,Smartphone,Average,Standard,Credit Card,Processing,2.0,Nokia,Senior,morning
299654,7157113,25148,Darlene Gomez,Teresa61@gmail.com,1114925786.0,572 Wagner Forge,Adelaide,New South Wales,83497,Australia,...,HarperCollins,Fiction,Bad,Standard,Credit Card,Delivered,1.0,Thriller,Senior,afternoon
299655,4733214,64906,Joanne Robinson,Emily29@gmail.com,5695197895.0,197 Donna Lodge Apt. 673,Melbourne,New South Wales,22949,Australia,...,Nestle,Snacks,Average,Express,Credit Card,Processing,2.0,Trail mix,Middle Age,morning
299656,8201755,48417,Kayla Stanley,Cindy37@gmail.com,5923171815.0,6026 Quinn Row Suite 313,Windsor,Ontario,68285,Canada,...,Sony,Smartphone,Average,Standard,Credit Card,Shipped,2.0,Xiaomi Mi,Senior,afternoon

In [146]:
print(f'Total sales : {df['Total_Amount'].sum()}')

Total sales : 399585398.5263326

In [147]:
df.groupby(['Year','Month'])['Total_Amount'].sum()

Year  Month
2023  April        3.305099e+07
      August       3.405824e+07
      December     3.366226e+07
      July         3.383606e+07
      June         3.271217e+07
      March        3.413037e+07
      May          3.342979e+07
      November     3.268253e+07
      October      3.356897e+07
      September    3.288064e+07
2024  February     3.190802e+07
      January      3.366537e+07
Name: Total_Amount, dtype: float64

In [148]:
df.groupby('Year')['Total_Amount'].sum()

Year
2023    3.340120e+08
2024    6.557338e+07
Name: Total_Amount, dtype: float64

In [149]:
df['Total_Purchases'].mean()

np.float64(5.362066072400887)

In [150]:
df['Total_Purchases'].sum()

np.int64(1565793)

In [151]:
df.groupby(['Year','Month'])['Total_Amount'].sum().sort_values(ascending=False).head(1)

Year  Month
2023  March    3.413037e+07
Name: Total_Amount, dtype: float64

In [152]:
df.groupby('Date')['Total_Amount'].sum().sort_values(ascending=False).head(10)

Date
2023-07-30    1.262794e+06
2024-02-22    1.237233e+06
2024-02-21    1.226890e+06
2023-09-02    1.215483e+06
2023-09-06    1.214934e+06
2023-10-18    1.206939e+06
2023-05-13    1.203225e+06
2023-04-17    1.198622e+06
2023-11-18    1.196340e+06
2023-12-25    1.194873e+06
Name: Total_Amount, dtype: float64

In [153]:
df['Customer_ID'].nunique()

86467

In [154]:
df.columns

Index(['Transaction_ID', 'Customer_ID', 'Name', 'Email', 'Phone', 'Address',
       'City', 'State', 'Zipcode', 'Country', 'Age', 'Gender', 'Income',
       'Customer_Segment', 'Date', 'Year', 'Month', 'Time', 'Total_Purchases',
       'Amount', 'Total_Amount', 'Product_Category', 'Product_Brand',
       'Product_Type', 'Feedback', 'Shipping_Method', 'Payment_Method',
       'Order_Status', 'Ratings', 'products', 'Age_Group'],
      dtype='object')

In [155]:
df.groupby('Customer_Segment')['Total_Amount'].sum()

Customer_Segment
New        1.204980e+08
Premium    8.410944e+07
Regular    1.946626e+08
Unknown    3.153814e+05
Name: Total_Amount, dtype: float64

In [156]:
df.groupby('Age_Group')['Total_Amount'].sum()

C:\Users\parih\AppData\Local\Temp\ipykernel_6296\2112126203.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby('Age_Group')['Total_Amount'].sum()

Age_Group
Young         1.103548e+08
Adult         8.909131e+07
Middle Age    1.108748e+08
Senior        8.926453e+07
Name: Total_Amount, dtype: float64

In [157]:
df.groupby('Gender')['Total_Amount'].sum()

Gender
Female    1.512860e+08
Male      2.482994e+08
Name: Total_Amount, dtype: float64

In [158]:
df['Customer_ID'].value_counts().apply(lambda x: 'New' if x==1 else 'Repeat').value_counts()

count
Repeat    75005
New       11462
Name: count, dtype: int64

In [159]:
df.groupby('Gender')['Customer_ID'].nunique()

Gender
Female    63659
Male      78057
Name: Customer_ID, dtype: int64

In [160]:
df.groupby('Income')['Customer_ID'].nunique()

Income
High      49902
Low       57949
Medium    67835
Name: Customer_ID, dtype: int64

In [161]:
df.groupby('Customer_ID')['Total_Amount'].sum().sort_values(ascending=False).head(20)

Customer_ID
48453    29241.776770
42972    25654.737170
12651    24757.661296
60092    23474.548838
90769    23446.433887
47382    23015.431924
10864    22944.471890
64700    22461.378993
72561    22368.392989
77135    22336.985038
97957    21990.533116
41641    21973.119734
59867    21790.548842
97526    21781.118302
91108    21659.307290
49847    21473.984650
28929    21289.042617
85369    21238.136378
14655    21025.438026
57673    20896.927770
Name: Total_Amount, dtype: float64

In [162]:
df.groupby('Customer_ID')['Total_Purchases'].sum().sort_values(ascending=False).head(10)

Customer_ID
48453    79
32249    79
42972    79
43157    79
39831    79
57673    78
53514    77
47382    76
19835    75
88690    75
Name: Total_Purchases, dtype: int64

In [163]:
df.groupby('Customer_ID')['Total_Amount'].mean()

Customer_ID
10000    1251.891589
10001    1627.292565
10002     820.802790
10003    1170.248223
10004    1178.258341
            ...
99995    1238.712532
99996    1353.608468
99997    1523.183387
99998    1369.967597
99999    2772.344245
Name: Total_Amount, Length: 86467, dtype: float64

In [164]:
df.groupby('Product_Category')['Total_Purchases'].sum().sort_values(ascending=False)

Product_Category
Electronics    369553
Grocery        346915
Clothing       284768
Books          282702
Home Decor     281855
Name: Total_Purchases, dtype: int64

In [165]:
df.groupby('Product_Brand')['Total_Purchases'].sum().sort_values(ascending=False).head()

Product_Brand
Pepsi        157805
Samsung       95538
Zara          95243
Coca-Cola     95130
Sony          94988
Name: Total_Purchases, dtype: int64

In [166]:
df.groupby('Product_Type')['Total_Purchases'].sum().sort_values(ascending=False).head()

Product_Type
Water          127813
Smartphone      95498
Non-Fiction     93781
Fiction         93712
T-shirt         63643
Name: Total_Purchases, dtype: int64

In [167]:
df.groupby('Product_Type')['Total_Purchases'].sum().sort_values(ascending=False).tail()

Product_Type
Tools          30994
Bedding        30938
Jacket         30784
Snacks         30429
BlueStar AC    11459
Name: Total_Purchases, dtype: int64

In [168]:
df.groupby('Product_Category')['Total_Amount'].sum()

Product_Category
Books          7.222677e+07
Clothing       7.259852e+07
Electronics    9.437960e+07
Grocery        8.844103e+07
Home Decor     7.193949e+07
Name: Total_Amount, dtype: float64

In [169]:
df.groupby('Product_Brand')['Total_Amount'].sum()

Product_Brand
Adidas               2.405030e+07
Apple                2.378900e+07
Bed Bath & Beyond    2.411140e+07
BlueStar             2.914504e+06
Coca-Cola            2.420917e+07
HarperCollins        2.417022e+07
Home Depot           2.398908e+07
IKEA                 2.376504e+07
Mitsubhisi           8.863939e+06
Nestle               2.391694e+07
Nike                 2.425437e+07
Penguin Books        2.397224e+07
Pepsi                4.024247e+07
Random House         2.399142e+07
Samsung              2.452627e+07
Sony                 2.435178e+07
Unknown              3.652209e+05
Whirepool            9.879695e+06
Zara                 2.422235e+07
Name: Total_Amount, dtype: float64

In [170]:
df.groupby('Product_Category')['Ratings'].mean()

Product_Category
Books          3.114060
Clothing       3.105757
Electronics    3.269475
Grocery        3.182322
Home Decor     3.112014
Name: Ratings, dtype: float64

In [171]:
df.groupby('Product_Brand')['Ratings'].mean()

Product_Brand
Adidas               3.105980
Apple                3.109883
Bed Bath & Beyond    3.117162
BlueStar             4.393321
Coca-Cola            3.102232
HarperCollins        3.117654
Home Depot           3.102247
IKEA                 3.117262
Mitsubhisi           3.875251
Nestle               3.111562
Nike                 3.112067
Penguin Books        3.112338
Pepsi                3.272437
Random House         3.112190
Samsung              3.135769
Sony                 3.121381
Unknown              3.145522
Whirepool            3.466419
Zara                 3.099488
Name: Ratings, dtype: float64

In [172]:
df.groupby('Country')['Total_Purchases'].sum()

Country
Australia    233946
Canada       233285
Germany      273860
UK           328864
USA          495838
Name: Total_Purchases, dtype: int64

In [173]:
df.groupby('State')['Total_Purchases'].sum().sort_values(ascending=False).head(10)

State
England            330292
Berlin             273830
New South Wales    233928
Ontario            233337
Connecticut        113980
Maine               63216
Georgia             49853
Kansas              28638
New Mexico          27643
New York             5185
Name: Total_Purchases, dtype: int64

In [174]:
df.groupby('City')['Total_Purchases'].sum().sort_values(ascending=False).head(10)

City
Chicago          114006
Portsmouth       107058
San Francisco     63025
Frankfurt         54030
Boston            49230
New York          28210
Fort Worth        27615
London            22994
Winnipeg          12431
Birmingham        12262
Name: Total_Purchases, dtype: int64

In [175]:
df.groupby('City')['Total_Amount'].sum().sort_values(ascending=False).head(20)

City
Chicago          2.886459e+07
Portsmouth       2.735176e+07
San Francisco    1.611221e+07
Frankfurt        1.372350e+07
Boston           1.255117e+07
New York         7.093244e+06
Fort Worth       7.010525e+06
London           5.929115e+06
Winnipeg         3.142933e+06
Plymouth         3.136044e+06
Birmingham       3.127401e+06
Calgary          3.111251e+06
Edmonton         3.110929e+06
Hanover          3.108370e+06
Edinburgh        3.090777e+06
Darwin           3.089426e+06
Mackay           3.088726e+06
Bielefeld        3.088006e+06
Victoria         3.086817e+06
Wollongong       3.077221e+06
Name: Total_Amount, dtype: float64

In [176]:
df['Payment_Method'].value_counts()

Payment_Method
Credit Card    86723
Debit Card     74812
Cash           70615
PayPal         59575
Unknown          288
Name: count, dtype: int64

In [177]:
df.groupby('Payment_Method')['Total_Amount'].sum()

Payment_Method
Cash           9.657451e+07
Credit Card    1.188743e+08
Debit Card     1.023365e+08
PayPal         8.141166e+07
Unknown        3.884605e+05
Name: Total_Amount, dtype: float64

In [178]:
df.groupby('Payment_Method')['Total_Purchases'].mean()

Payment_Method
Cash           5.358975
Credit Card    5.365313
Debit Card     5.360276
PayPal         5.362384
Unknown        5.541667
Name: Total_Purchases, dtype: float64

In [193]:
import mysql.connector
from urllib.parse import quote_plus
from sqlalchemy import create_engine

In [194]:
from sqlalchemy import create_engine
from sqlalchemy.engine import URL

url = URL.create(
    drivername="mysql+pymysql",
    username="root",
    password="#Pssa@9404#",
    host="localhost",
    database="retailer_analysis"
)

engine = create_engine(url)

In [195]:
with engine.connect() as conn:
    print("Connected Successfully!")

Connected Successfully!

In [196]:
df.to_sql(
    name="retailer_analysis",
    con=engine,
    if_exists="replace",
    index=False
)

292013